siteTitle = "Benjamin Cooper | Work, Research, and Me"
siteDescr = ""
siteAuthor = "Benjamin Cooper"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "https://github.com/BenjaminKCooper"
siteEmailUrl = "benjamin.k.cooper.18@dartmouth.edu"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""
