siteTitle = "Humbug Chapbook"
siteDescr = ""
siteAuthor = "Benjamin Cooper"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteEmailUrl = "benjamin.k.cooper.18@dartmouth.edu"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = ""
